# Define an access log for VirtualHosts that don't define their own logfile
# Fedora version: /etc/httpd/conf-available/other-vhosts-access-log.conf
# Enable with: sudo a2enconf other-vhosts-access-log
#
# NOTE: Debian defines the vhost_combined LogFormat in apache2.conf.
#       Fedora does not, so it is defined here first.
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined

Include /etc/apache2/elRewrite.conf
ErrorLog /LOVE/earth.love/_LOGS/vhost_error.log
CustomLog "| /ELBIN/vhostpipeLOGSsplit.pl LOG  /LOVE/earth.love/_LOGS/vhost_access.log"     vhost_combined "expr=(-z reqenv('hacklog') && -z reqenv('botlog'))"
CustomLog "| /ELBIN/vhostpipeLOGSsplit.pl HACK /LOVE/earth.love/_LOGS/vhost_accessHACK.log" vhost_combined env=hacklog
CustomLog "| /ELBIN/vhostpipeLOGSsplit.pl BOT  /LOVE/earth.love/_LOGS/vhost_accessBOT.log"  vhost_combined env=botlog

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
